# Generated by Django 3.0.7 on 2020-06-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dato',
            index=models.Index(fields=['location'], name='core_dato_locatio_2d856d_idx'),
        ),
        migrations.AddIndex(
            model_name='dato',
            index=models.Index(fields=['-fecha'], name='core_dato_fecha_fe97f5_idx'),
        ),
    ]
