# Generated by Django 3.0.7 on 2020-06-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200616_1537'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dato',
            name='core_dato_fecha_fe97f5_idx',
        ),
        migrations.RemoveField(
            model_name='dato',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='dato',
            name='location',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
